### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [Taniadrina/prj-rev-bwfs-dasmoto#4]
Great job on this project as it was very well written and structured.

++ Consistency on whitespace and indentations.
++ Relative paths over absolute paths.
++ Accuracy in following design spec.

-- IDs before classes.

Overall, amazing work! Keep it up!

Grade: Meets expectation.

**Comment by Taniadrina** [comment]
Thanks a lot, 

I'll keep in mind the improvements that I have to make
